augmenter_model: v0.3
camerasToUse:
- all
filterFrequency: default
imageUpsampleFactor: 4
openSimModel: LaiUhlrich2022_adjusted
poseDetector: OpenPose
resolutionPoseDetection: 1x736
scalingSetup: upright_standing_pose
verticalOffset: -0.25647941669464114
